const THEMES=["Agriculture & alimentation","Eau & assainissement","Énergie & climat","Gestion des ressources naturelles","Développement économique","Santé & services sociaux","Gouvernance territoriale","Mobilités & migrations","Risques naturels","Cohésion sociale"];
const ORGS=["AVSF","GERES","GRDR","GRET","Le Partenariat","ADOS"];
const FUNDERS=["Fondation de France","AFD","Union européenne","Agence de l'eau","Coopération suisse","Collectivités territoriales"];
const PARTNERS=["OMVS","Collectivité locale","Organisation paysanne","Service technique national","Association locale","Université / recherche","Chambre consulaire"];
const ODD=["ODD 2","ODD 5","ODD 6","ODD 7","ODD 8","ODD 11","ODD 13","ODD 15","ODD 16","ODD 17"];

// Géométries simplifiées de démonstration, volontairement non officielles.
const admin2Defs=[
["Sénégal","Saint-Louis","Saint-Louis",[-16.7,15.75,-15.8,16.35]], ["Sénégal","Saint-Louis","Dagana",[-16.1,16.0,-14.9,16.7]], ["Sénégal","Saint-Louis","Podor",[-15.3,16.1,-13.7,16.85]],
["Sénégal","Matam","Matam",[-14.1,15.0,-12.7,16.1]], ["Sénégal","Matam","Kanel",[-13.4,14.4,-12.0,15.45]], ["Sénégal","Tambacounda","Bakel",[-12.8,13.9,-11.4,14.95]],
["Mauritanie","Trarza","Rosso",[-16.3,16.2,-15.1,17.0]], ["Mauritanie","Brakna","Aleg",[-14.8,16.5,-13.0,17.4]], ["Mauritanie","Gorgol","Kaédi",[-13.7,15.8,-12.0,16.8]], ["Mauritanie","Guidimakha","Sélibaby",[-12.7,15.0,-11.4,15.9]],
["Mali","Kayes","Kayes",[-11.8,14.1,-10.8,15.0]], ["Mali","Kayes","Bafoulabé",[-11.5,13.2,-10.2,14.2]], ["Mali","Kayes","Yélimané",[-11.4,14.6,-10.2,15.6]], ["Mali","Kayes","Kéniéba",[-12.3,12.7,-11.0,13.8]], ["Mali","Koulikoro","Kita",[-10.1,12.6,-8.7,13.9]],
["Guinée","Labé","Labé",[-12.6,11.0,-11.3,12.2]], ["Guinée","Labé","Mali",[-12.5,11.8,-11.2,13.0]], ["Guinée","Mamou","Mamou",[-12.2,9.9,-10.8,11.2]], ["Guinée","Mamou","Dalaba",[-12.3,10.3,-11.2,11.3]], ["Guinée","Faranah","Dabola",[-11.3,10.4,-10.0,11.6]]
];

function polyFromBox(b,i){const [x1,y1,x2,y2]=b; const j=(i%3)*.06; return [[[x1+j,y1],[x2,y1+.04],[x2-.05,y2-j],[x1,y2-.02],[x1+j,y1]]];}
const admin2Geo={type:"FeatureCollection",features:admin2Defs.map((d,i)=>({type:"Feature",properties:{country:d[0],region:d[1],name:d[2],id:"a"+i},geometry:{type:"Polygon",coordinates:polyFromBox(d[3],i)}}))};

function seeded(n){let x=Math.sin(n*999.1)*10000;return x-Math.floor(x)}
function pick(arr,n){return arr[Math.floor(seeded(n)*arr.length)]}
function makeProjects(){let out=[];let id=1;for(let a=0;a<admin2Defs.length;a++){let count=2+Math.floor(seeded(a+9)*5);for(let j=0;j<count;j++){let n=a*11+j+1;let start=2021+Math.floor(seeded(n+2)*5);let duration=1+Math.floor(seeded(n+3)*3);let end=Math.min(2026,start+duration);let org=pick(ORGS,n+4), theme=pick(THEMES,n+5);let theme2=seeded(n+6)>.68?pick(THEMES,n+16):null;let status=end>=2026&&seeded(n+8)>.35?"En cours":"Terminé";let beneficiaries=250+Math.floor(seeded(n+10)*9800);let d=admin2Defs[a];out.push({id:id++,title:["Renforcement des filières locales","Résilience des territoires riverains","Accès durable aux services essentiels","Appui aux dynamiques communautaires","Adaptation climatique et ressources naturelles","Développement économique inclusif"][Math.floor(seeded(n+12)*6)]+" — "+d[2],country:d[0],region:d[1],admin2:d[2],organization:org,themes:[theme,...(theme2&&theme2!==theme?[theme2]:[])],funder:pick(FUNDERS,n+7),partner:pick(PARTNERS,n+9),status,start,end,beneficiaries,budget:45000+Math.floor(seeded(n+13)*530000),odd:[pick(ODD,n+14),pick(ODD,n+15)].filter((v,i,a)=>a.indexOf(v)===i),summary:"Projet de démonstration illustrant une intervention territoriale multi-acteurs dans le Bassin du Fleuve Sénégal. Les données présentées sont fictives et servent uniquement à tester l’ergonomie de la WebMap."});}}
return out}
let projects=makeProjects();
const historical=admin2Geo.features.filter((_,i)=>i%2===0).map((f,i)=>({feature:f,count:3+Math.floor(seeded(i+41)*15)}));

const map=L.map('map',{zoomControl:false}).setView([14.7,-12.7],5);
L.control.zoom({position:'bottomright'}).addTo(map);
const street=L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(map);
const topo=L.tileLayer('https://{s}.tile.opentopomap.org/{z}/{x}/{y}.png',{maxZoom:17,attribution:'© OpenTopoMap'});
L.control.layers({"Plan":street,"Relief":topo},null,{position:'topright'}).addTo(map);
let geoLayer=L.geoJSON(admin2Geo).addTo(map), histLayer=L.layerGroup();

const $=q=>typeof q==='string'&&q.startsWith('.')?document.querySelector(q):document.getElementById(q);
const ids=["countryFilter","regionFilter","admin2Filter","orgFilter","statusFilter","themeFilter","funderFilter","partnerFilter","yearStart","yearEnd","metricSelect"];
let sortDesc=true, current=[];
function unique(a){return [...new Set(a)].sort((x,y)=>x.localeCompare(y,'fr'))}
function fillSelect(id,values,keep=true){let el=$(id), cur=keep?el.value:""; let first=el.options[0]?.outerHTML||'<option value="">Tous</option>'; el.innerHTML=first+values.map(v=>`<option>${v}</option>`).join(''); if(values.includes(cur))el.value=cur;}
fillSelect('countryFilter',unique(projects.map(p=>p.country)));fillSelect('orgFilter',ORGS);fillSelect('themeFilter',THEMES);fillSelect('funderFilter',FUNDERS);fillSelect('partnerFilter',PARTNERS);
for(let y=2021;y<=2026;y++){ $('yearStart').add(new Option(y,y)); $('yearEnd').add(new Option(y,y)); } $('yearStart').value=2021;$('yearEnd').value=2026;

function syncGeoFilters(){let c=$('countryFilter').value,r=$('regionFilter').value;let regs=unique(projects.filter(p=>!c||p.country===c).map(p=>p.region));fillSelect('regionFilter',regs);r=$('regionFilter').value;let a2=unique(projects.filter(p=>(!c||p.country===c)&&(!r||p.region===r)).map(p=>p.admin2));fillSelect('admin2Filter',a2);}
function filtered(){let ys=+$('yearStart').value,ye=+$('yearEnd').value;return projects.filter(p=>(!$('countryFilter').value||p.country===$('countryFilter').value)&&(!$('regionFilter').value||p.region===$('regionFilter').value)&&(!$('admin2Filter').value||p.admin2===$('admin2Filter').value)&&(!$('orgFilter').value||p.organization===$('orgFilter').value)&&(!$('statusFilter').value||p.status===$('statusFilter').value)&&(!$('themeFilter').value||p.themes.includes($('themeFilter').value))&&(!$('funderFilter').value||p.funder===$('funderFilter').value)&&(!$('partnerFilter').value||p.partner===$('partnerFilter').value)&&p.end>=ys&&p.start<=ye)}
function statsFor(name){let a=current.filter(p=>p.admin2===name);return {projects:a.length,beneficiaries:a.reduce((s,p)=>s+p.beneficiaries,0),organizations:new Set(a.map(p=>p.organization)).size,partners:new Set(a.map(p=>p.partner)).size,funders:new Set(a.map(p=>p.funder)).size}}
function metricValue(s){return s[$('metricSelect').value]||0}
function color(v,max){let t=max?Math.min(1,v/max):0; if(t===0)return '#eef2ef'; if(t<.25)return '#cfe0d3'; if(t<.5)return '#9fc2aa'; if(t<.75)return '#65967a'; return '#2c6e5a'}
function renderMap(){let vals=admin2Geo.features.map(f=>metricValue(statsFor(f.properties.name))),max=Math.max(0,...vals);geoLayer.clearLayers();geoLayer=L.geoJSON(admin2Geo,{style:f=>{let s=statsFor(f.properties.name),v=metricValue(s);return {color:'#fff',weight:1.5,fillColor:color(v,max),fillOpacity:.86}},onEachFeature:(f,l)=>{let s=statsFor(f.properties.name);l.bindTooltip(`${f.properties.name} · ${s.projects} projet${s.projects>1?'s':''}`,{sticky:true});l.on('click',()=>{let html=`<div class="popup-title">${f.properties.name}</div><div style="font-size:9px;color:#71817c">${f.properties.region} · ${f.properties.country}</div><div class="popup-stats"><div class="popup-stat"><strong>${s.projects}</strong>Projets</div><div class="popup-stat"><strong>${fmt(s.beneficiaries)}</strong>Bénéficiaires</div><div class="popup-stat"><strong>${s.organizations}</strong>Intervenants</div><div class="popup-stat"><strong>${s.partners}</strong>Partenaires</div></div><span class="popup-link" onclick="focusAdmin2('${f.properties.name.replaceAll("'","\\'")}')">Filtrer sur cette unité →</span>`;l.bindPopup(html).openPopup()})}}).addTo(map);$('legendMax').textContent=fmt(max);$('legendMin').textContent='0';$('legendMetric').textContent=$('metricSelect').selectedOptions[0].textContent;}
window.focusAdmin2=name=>{ $('admin2Filter').value=name; apply();map.closePopup();}
function renderHistorical(){histLayer.clearLayers();if(!$('historicalToggle').checked){if(map.hasLayer(histLayer))map.removeLayer(histLayer);return}historical.forEach(h=>{let c=L.geoJSON(h.feature).getBounds().getCenter();L.circleMarker(c,{radius:5+Math.sqrt(h.count)*1.6,color:'#7c5b8e',weight:1,fillColor:'#a77cba',fillOpacity:.65}).bindTooltip(`Historique 2010–2020 : ${h.count} projets`).addTo(histLayer)});histLayer.addTo(map)}
function fmt(n){return Number(n||0).toLocaleString('fr-FR')}
function renderKpis(){ $('visibleProjects').textContent=`${current.length} projet${current.length>1?'s':''}`;$('kpiProjects').textContent=current.length;$('kpiBeneficiaries').textContent=fmt(current.reduce((s,p)=>s+p.beneficiaries,0));$('kpiOrgs').textContent=new Set(current.map(p=>p.organization)).size;$('kpiPartners').textContent=new Set(current.map(p=>p.partner)).size;}
function renderThemes(){let counts=THEMES.map(t=>[t,current.filter(p=>p.themes.includes(t)).length]).filter(x=>x[1]).sort((a,b)=>b[1]-a[1]);let max=Math.max(1,...counts.map(x=>x[1]));$('themeCount').textContent=`${counts.length} actives`;$('themeChart').innerHTML=counts.slice(0,7).map(([t,v])=>`<div class="bar-row"><span class="bar-label" title="${t}">${t}</span><span class="bar-track"><span class="bar-fill" style="display:block;width:${v/max*100}%"></span></span><span class="bar-value">${v}</span></div>`).join('')||'<span class="small-note">Aucune donnée</span>';}
function renderYears(){let years=[2021,2022,2023,2024,2025,2026], vals=years.map(y=>current.filter(p=>p.start<=y&&p.end>=y).length),max=Math.max(1,...vals);$('yearChart').innerHTML=years.map((y,i)=>`<div class="spark-col"><div title="${vals[i]} projets actifs" class="spark-bar" style="height:${Math.max(4,vals[i]/max*58)}px"></div><span>${String(y).slice(2)}</span></div>`).join('')}
function renderList(){let arr=[...current].sort((a,b)=>sortDesc?b.start-a.start:a.start-b.start);$('projectList').innerHTML=arr.slice(0,28).map(p=>`<article class="project-item" data-id="${p.id}"><span class="tag">${p.organization}</span> <span class="tag ${p.status==='Terminé'?'done':'status'}">${p.status}</span><h4>${p.title}</h4><div class="project-meta"><span>${p.admin2} · ${p.country}</span><span>${p.start}–${p.end}</span></div></article>`).join('')||'<p class="small-note">Aucun projet ne correspond aux filtres.</p>';document.querySelectorAll('.project-item').forEach(el=>el.onclick=()=>openProject(+el.dataset.id))}
function apply(){syncGeoFilters();current=filtered();renderKpis();renderThemes();renderYears();renderList();renderMap();renderHistorical();}
ids.forEach(id=>$(id).addEventListener('change',apply));$('historicalToggle').addEventListener('change',renderHistorical);
$('sortBtn').onclick=()=>{sortDesc=!sortDesc;renderList()};
function openProject(id){let p=projects.find(x=>x.id===id);if(!p)return;$('drawerContent').innerHTML=`<span class="eyebrow">FICHE PROJET</span><h2>${p.title}</h2><div><span class="tag">${p.organization}</span> <span class="tag ${p.status==='Terminé'?'done':'status'}">${p.status}</span></div><p class="drawer-summary">${p.summary}</p><div class="detail-grid"><div class="detail"><span>Territoire</span><strong>${p.admin2}, ${p.country}</strong></div><div class="detail"><span>Période</span><strong>${p.start}–${p.end}</strong></div><div class="detail"><span>Bénéficiaires</span><strong>${fmt(p.beneficiaries)}</strong></div><div class="detail"><span>Budget global</span><strong>${fmt(p.budget)} €</strong></div><div class="detail"><span>Bailleur</span><strong>${p.funder}</strong></div><div class="detail"><span>Partenaire</span><strong>${p.partner}</strong></div></div><h3>Thématique(s)</h3><p>${p.themes.join(' · ')}</p><h3>Objectifs de développement durable</h3><p>${p.odd.join(' · ')}</p>`;$('projectDrawer').classList.add('open');$('drawerBackdrop').classList.add('open')}
function closeDrawer(){$('projectDrawer').classList.remove('open');$('drawerBackdrop').classList.remove('open')}$('drawerClose').onclick=closeDrawer;$('drawerBackdrop').onclick=closeDrawer;
function openModal(){$('aboutModal').classList.add('open');$('modalBackdrop').classList.add('open')};function closeModal(){$('aboutModal').classList.remove('open');$('modalBackdrop').classList.remove('open')}$('btnAbout').onclick=openModal;$('modalClose').onclick=closeModal;$('modalBackdrop').onclick=closeModal;
$('btnReset').onclick=()=>{['countryFilter','regionFilter','admin2Filter','orgFilter','statusFilter','themeFilter','funderFilter','partnerFilter'].forEach(id=>$(id).value='');$('yearStart').value=2021;$('yearEnd').value=2026;$('metricSelect').value='projects';$('historicalToggle').checked=false;map.setView([14.7,-12.7],5);apply();toast('Filtres réinitialisés')};
$('btnFilters').onclick=()=>$('.left-panel')?.classList.toggle('open');
function toast(msg){let t=$('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
$('btnImport').onclick=()=>$('csvInput').click();$('csvInput').addEventListener('change',e=>{let file=e.target.files[0];if(!file)return;let r=new FileReader();r.onload=()=>importCSV(r.result);r.readAsText(file,'utf-8')});
function parseCSVLine(line,sep){let out=[],cur='',q=false;for(let i=0;i<line.length;i++){let ch=line[i];if(ch==='"'){if(q&&line[i+1]==='"'){cur+='"';i++}else q=!q}else if(ch===sep&&!q){out.push(cur.trim());cur=''}else cur+=ch}out.push(cur.trim());return out}
function importCSV(txt){try{let lines=txt.replace(/^\uFEFF/,'').split(/\r?\n/).filter(Boolean);if(lines.length<2)throw Error('fichier vide');let sep=lines[0].includes(';')?';':',';let headers=parseCSVLine(lines[0],sep).map(x=>x.toLowerCase());let req=['title','country','region','admin2','organization','theme','funder','partner','status','start','end','beneficiaries'];let missing=req.filter(x=>!headers.includes(x));if(missing.length)throw Error('colonnes manquantes : '+missing.join(', '));let added=0;for(let i=1;i<lines.length;i++){let v=parseCSVLine(lines[i],sep),o={};headers.forEach((h,k)=>o[h]=v[k]||'');if(!o.title)continue;projects.push({id:Math.max(...projects.map(p=>p.id))+1,title:o.title,country:o.country,region:o.region,admin2:o.admin2,organization:o.organization,themes:o.theme.split('|').filter(Boolean),funder:o.funder,partner:o.partner,status:o.status,start:+o.start,end:+o.end,beneficiaries:+o.beneficiaries||0,budget:+o.budget||0,odd:(o.odd||'').split('|').filter(Boolean),summary:o.summary||'Projet importé depuis CSV.'});added++}fillSelect('countryFilter',unique(projects.map(p=>p.country)));fillSelect('orgFilter',unique(projects.map(p=>p.organization)));fillSelect('themeFilter',unique(projects.flatMap(p=>p.themes)));fillSelect('funderFilter',unique(projects.map(p=>p.funder)));fillSelect('partnerFilter',unique(projects.map(p=>p.partner)));apply();toast(`${added} projet${added>1?'s':''} importé${added>1?'s':''}`)}catch(err){toast('Import impossible : '+err.message)}}
apply();
